@startuml
skinparam BoxPadding 10

participant "ProAV Person"
participant "NMOS Controller"
box "Gateway Receiver 1"
participant "Rcv 1 IS-04"
participant "Rcv 1 IS-05"
end box
box "Gateway Receiver 2"
participant "Rcv 2 IS-04"
participant "Rcv 2 IS-05"
end box
box "Gateway Sender"
participant "Snd IS-04"
participant "Snd Sink API"
participant "Snd IS-05"
end box

"ProAV Person" -> "NMOS Controller": 1. Choose Sender and Receivers
"NMOS Controller" -> "Rcv 1 IS-04": 2. Get Receiver Caps 1
"NMOS Controller" -> "Rcv 2 IS-04": 3. Get Receiver Caps 2
"NMOS Controller" -> "Snd Sink API": 4. Put Media Profiles
"NMOS Controller" -> "Snd IS-05": 5. Start Stream
"NMOS Controller" -> "Rcv 1 IS-05": 6. Receive Stream
"NMOS Controller" -> "Rcv 2 IS-05": 7. Recieve Stream
@enduml
