@startuml
autonumber

participant "HDMI Sink"
participant "NMOS Device Controller"
participant "NMOS Node"

"HDMI Sink" <- "NMOS Device Controller": Request EDID
"HDMI Sink" -> "NMOS Device Controller": Give EDID
"NMOS Device Controller" -> "NMOS Device Controller": Update Sink Metadata Processing API content
"NMOS Node" <- "NMOS Device Controller": Update Receiver and Receiver Capabilities
@enduml
