@startuml
autonumber
participant "HDMI Sink"
participant "NMOS Device Controller"
participant "NMOS Controller"
participant "IT Person"

"HDMI Sink" <- "NMOS Device Controller": Request EDID
"HDMI Sink" -> "NMOS Device Controller": Give EDID
"NMOS Device Controller" -> "NMOS Device Controller": Update Sink Metadata Processing API content
"NMOS Controller" <- "IT Person": Get EDID binary
"NMOS Controller" -> "NMOS Device Controller": Request EDID binary
"NMOS Controller" <- "NMOS Device Controller": Return EDID binary
"NMOS Controller" -> "IT Person": Return EDID binary
"NMOS Controller" <- "IT Person": Get Sink
"NMOS Controller" -> "NMOS Device Controller": Request Sink
"NMOS Controller" <- "NMOS Device Controller": Return Sink
"NMOS Controller" -> "IT Person": Return Sink
@enduml
