@startuml
participant "HDMI Sink"
participant "EDID Processing API"
participant "IPMX Control System"
participant "ProAV Staff"

"HDMI Sink" <- "EDID Processing API": 1. Read EDID
"HDMI Sink" -> "EDID Processing API": return
"EDID Processing API" -> "EDID Processing API": 2. Parse EDID
"EDID Processing API" -> "EDID Processing API": 3. Update Sink
"IPMX Control System" <- "ProAV Staff": 4. Get Raw EDID
"IPMX Control System" -> "EDID Processing API": 5. Get Raw EDID
"IPMX Control System" <- "EDID Processing API": return
"IPMX Control System" -> "ProAV Staff": return
"IPMX Control System" <- "ProAV Staff": 5. Get Parsed EDID Info
"IPMX Control System" -> "EDID Processing API": 6. Get Parsed EDID Info
"IPMX Control System" <- "EDID Processing API": return
"IPMX Control System" -> "ProAV Staff": return
@enduml
