@startuml
participant "HDMI Destination"
participant "IPMX Device Control API: IPMX Device Controller"
participant "IPMX Control System"
participant "Pro AV Staff"

"HDMI Destination" <- "IPMX Device Control API: IPMX Device Controller": 1. Read EDID
"HDMI Destination" -> "IPMX Device Control API: IPMX Device Controller": return
"IPMX Device Control API: IPMX Device Controller" -> "IPMX Device Control API: IPMX Device Controller": 2. Parse EDID
"IPMX Device Control API: IPMX Device Controller" -> "IPMX Device Control API: IPMX Device Controller": 3. Update IPMX Device Control API Destination
"IPMX Control System" <- "Pro AV Staff": 4. Get Raw EDID
"IPMX Control System" -> "IPMX Device Control API: IPMX Device Controller": 5. Get Raw EDID
"IPMX Control System" <- "IPMX Device Control API: IPMX Device Controller": return
"IPMX Control System" -> "Pro AV Staff": return
"IPMX Control System" <- "Pro AV Staff": 5. Get Parsed EDID Info
"IPMX Control System" -> "IPMX Device Control API: IPMX Device Controller": 6. Get Parsed EDID Info
"IPMX Control System" <- "IPMX Device Control API: IPMX Device Controller": return
"IPMX Control System" -> "Pro AV Staff": return
@enduml
