@startuml
autonumber
skinparam BoxPadding 10

participant "HDMI Source"
participant "NMOS Device Controller"
participant "NMOS Controller"

"NMOS Controller" -> "NMOS Device Controller": Put Media Profiles
"NMOS Controller" <- "NMOS Device Controller": Return 200
"HDMI Source" <- "NMOS Device Controller": Present EDID
"NMOS Device Controller" -> "NMOS Node": Update Sources, Flows and Senders
@enduml
