@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_LEFT_RIGHT()

Person(person, "IT Staff", "Responsible for setting up HDMI presentations")

System_Ext(ics, "NMOS Controller", "NMOS Controller")
System_Ext(hdmi, "HDMI Sink", "HDMI Sink")
System_Ext(switch, "Network Switch", "Network Switch")

System_Boundary(proav, "Gateway Receiver") {
    Container(gw, "Gateway Receiver", "IS-04 Device", "Converts an IP stream to HDMI Video and Audio")
    Container(ipmx_controller, "NMOS Device Controller", "Sink Metadata Processing API", "")
}

BiRel(person, ics, "GUI", "Graphical User Interface")
Rel(ics, ipmx_controller, "Get EDID info", "RESTful API")
Rel(hdmi, ipmx_controller, "Sends EDID", "HDMI DDC")
Rel(ipmx_controller, gw, "Sets up IS-04 Receivers", "IS-04")
Rel(ics, gw, "Subscribe to Sender's Flows", "IS-05")
Rel(gw, hdmi, "HDMI Video and Audio", "HDMI")
Rel(switch, gw, "Media Flows", "ST 2110")
@enduml
