@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_LEFT_RIGHT()

Person(person, "IT Staff", "Responsible for setting up HDMI presentations")

System_Ext(ics, "NMOS Controller", "NMOS Controller")

System_Boundary(proav, "NMOS System") {

    Container(dec_1, "Gateway Receiver", "IS-04 Node", "Gateway Receiver 1")
    Container(dec_2, "Gateway Receiver", "IS-04 Node", "Gateway Receiver 2")
    Container(dec_3, "Gateway Receiver", "IS-04 Node", "Gateway Receiver 3")
    Container(Snd, "Gateway Sender", "IS-04 Node", "Gateway Receiver")
    Container(rds, "NMOS RDS", "IS-04 RDS", "NMOS Registration and Discovery Service")
    Container(switch, "Network Switch", "Network Switch")
}

BiRel(person, ics, "GUI", "Graphical User Interface")
BiRel(dec_1, switch, "ST 2110 Flows", "IP Media, Event, Control")
BiRel(dec_2, switch, "ST 2110 Flows", "IP Media, Event, Control")
BiRel(dec_3, switch, "ST 2110 Flows", "IP Media, Event, Control")
BiRel(Snd, switch, "ST 2110 Flows", "IP Media, Event, Control")
BiRel(rds, switch, "HTTP traffic")
Rel(ics, switch, "Status and Control", "NMOS RESTful APIs, SNMPv3")
@enduml
