@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_LEFT_RIGHT()

Person(person, "IT Staff", "Responsible for setting up HDMI presentations")

System_Ext(ics, "NMOS Controller", "NMOS Controller")
System_Ext(hdmi, "HDMI Source", "HDMI Source")
System_Ext(switch, "Network Switch", "Network Switch")

System_Boundary(proav, "Gateway Sender") {
    Container(gw, "Gateway Sender", "IS-04 Device", "Converts HDMI Video and Audio to an IP stream")
    Container(ipmx_controller, "NMOS Device Controller", "Sink Metadata Processing API", "")
}

BiRel(person, ics, "GUI", "Graphical User Interface")
Rel(ics, ipmx_controller, "Control Media Profile(s)", "RESTful API")
Rel(ipmx_controller, hdmi, "Set EDID and other HDMI Source Parameters", "HDMI DDC")
Rel(ipmx_controller, gw, "Setup Sources, Flows and Senders", "IS-04")
Rel(ics, gw, "Start transmitting", "IS-05")
Rel(hdmi, gw, "HDMI Video and Audio", "HDMI")
Rel(gw, switch, "Video Flow", "ST 2110-20")
@enduml
