@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(person, "IT Staff", "Responsible for setting up and Controlling the NMOS System")
System_Ext(ics, "NMOS Controller")
System(proav, "NMOS System")

BiRel(person, ics, "GUI", "Graphical User Interface")
BiRel(ics, proav, "Network", "RESTful APIs, SNMPv3")
@enduml
