name: Render PlantUML diagrams
on:
  workflow_dispatch:

  push:
    branches-ignore:
        - 'v[0-9]+.[0-9]+-dev'
        - 'v[0-9]+.[0-9]+.x'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Render PlantUML diagrams
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: docs/images/svg
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
